### ISSUE TITLE
Consider prefixing intentional duplicates when posting to openradar

### ISSUE THREAD

**Issue by hannesoid** [br1sk/brisk#101]
When browsing openradar it can be hard to see if you are looking at an original issue or a duplicate if they have the same name:

![bildschirmfoto 2017-07-10 um 13 22 40](https://user-images.githubusercontent.com/1856655/28016467-bdbca086-6574-11e7-8e7f-9140782039c3.png)
In this list there are lots of duplicates but it is hard to spot from the overview.

### Proposed solution
Prefix the generated OpenRadard entry with something like 
-  `[Brisk-Duplicated] `

Alternatives
-  `Duplicate: `
-  `[Duplicate] `
-  `[Brisk-Duplicate] `
- extend openradar itself to support and indicate this somehow

**Comment by keith** [comment]
Thanks for filing this! I agree that this is pretty weird. I wonder if this will be solved _enough_ by https://github.com/br1sk/brisk/issues/106 that we won't need to add anything custom for this?

Otherwise I think my preferred option would be to put a non-Brisk specific modifier to the title like `Duplicate:`

**Comment by hannesoid** [comment]
Yes https://github.com/br1sk/brisk/issues/106 will probably prevent the issue from occurring. I think a `Duplicate:` prefix would still not be wrong, or are there arguments against it? But lower priority now.

**Comment by keith** [comment]
Not really, just generally feel a little weird about changing the text in people's radars if we can avoid it.

**Comment by hannesoid** [comment]
After experimenting a bit I think https://github.com/br1sk/brisk/issues/106 solves it well enough 👍, so I will close this
