### ISSUE TITLE
Option to not post dupes to OpenRadar

### ISSUE THREAD

**Issue by sberrevoets** [br1sk/brisk#106]
Any radars I file myself I want on OpenRadar, but if I'm duping another radar that's already on OpenRadar, it would be nice if Brisk didn't post the dupe there as well.

**Comment by keith** [comment]
I think the best solution here is that when you "restore" a radar, either from a file or from a duplicate, we default to not crosspost.

**Comment by keith** [comment]
Fixed in https://github.com/br1sk/brisk/pull/110

**Comment by keith** [comment]
Released in 1.1.0
