### ISSUE TITLE
Changelog should be in rich text

### ISSUE THREAD

**Issue by ZevEisenberg** [br1sk/brisk#111]
Any way to get Sparkle to parse Markdown?

![screen shot 2017-07-31 at 12 28 56 pm](https://user-images.githubusercontent.com/464574/28796089-37c2e3ae-760a-11e7-9127-1cf5ec51fb5d.png)

**Comment by keith** [comment]
Blah. Yea. I think what I really need to do here is just render this markdown as HTML and use that as the changelog. That would also fix the artifact of being able to see the `master` notes here

**Comment by ZevEisenberg** [comment]
It could be a nice enhancement to Sparkle to do this automatically, especially if it's pulling directly from your GitHub tags. But I'm not sure if it is, or if you're maintaining the change log files on a server yourself.

**Comment by keith** [comment]
Right now it's just pointing the to changelog on master, which is why it includes the master one. I should instead have it point to the tags for sure, that would help at least the noise at the top

**Comment by keith** [comment]
I've improved the second problem here by pointing to the changelog at the tag of the release:

![image](https://user-images.githubusercontent.com/283886/29499027-ae13516c-85bc-11e7-970d-6a84fa56f623.png)

**Comment by keith** [comment]
Gonna close this one now that at least the info doesn't include newer stuff than what is actually in the release. We'll live with the monospacing
