### ISSUE TITLE
Feature Request: Add "Radar" to app name to index with Spotlight

### ISSUE THREAD

**Issue by HarshilShah** [br1sk/brisk#112]
It would be nice if the app's name could have "radar" within it. This would make it easier to search using spotlight. Maybe this could be inserted as a subtitle ("Brisk: Quickly File Radars" or something like that)

Muscle memory has me typing "radar" in the Safari omnibar which autofills the rest and opens the website, so having to just do the same from Spotlight would be nice.

**Comment by kiliankoe** [comment]
But 📡's URL is bugreport.apple.com 🙈

**Comment by HarshilShah** [comment]
radar.apple.com does redirect to it though. I do wonder where the name Radar came from though 🤔

**Comment by kiliankoe** [comment]
Oh, interesting! I only knew about the bugreporter.apple.com redirect 😊

**Comment by ZevEisenberg** [comment]
You should be able to add Radar to the spotlight metadata section of the Get Info window on your machine. Would still be cool to add it to the app as a whole, though.

**Comment by HarshilShah** [comment]
Didn't know this was a thing. Way better now, thanks!

**Comment by keith** [comment]
If there's anything we can do on the brisk side I'd be happy to merge a PR, closing this in the meantime
