### ISSUE TITLE
Layout breaks with super long notes field

### ISSUE THREAD

**Issue by keith** [br1sk/brisk#113]
![screen shot 2017-08-07 at 15 10 58](https://user-images.githubusercontent.com/283886/29047937-146582f8-7b83-11e7-9318-3067e0914af5.png)

Just open this file in Brisk to reproduce:
[Open source XCBuild!.brisk.zip](https://github.com/br1sk/brisk/files/1206314/Open.source.XCBuild.brisk.zip)

**Comment by keith** [comment]
In general we need to re-work the autolayout here, since this has always been a bit broken. Related: https://github.com/br1sk/brisk/issues/33

**Comment by Augustyniak** [comment]
Somehow related. 

1. I've tried to dupe a radar.
2. Noticed a broken UI as on the screenshot in the description of the ticket.
3. Started resizing a window.
4. Ended up with:

<img width="766" alt="screen shot 2017-08-07 at 3 19 12 pm" src="https://user-images.githubusercontent.com/4410346/29048164-2cf5ca52-7b84-11e7-94d9-58948d8c2bdb.png">

**Comment by keith** [comment]
Autolayout is definitely exploding here

**Comment by keith** [comment]
Fixed in https://github.com/br1sk/brisk/pull/117
