### ISSUE TITLE
Radar creation fails when data consent alert is displayed

### ISSUE THREAD

**Issue by vytis** [br1sk/brisk#137]
It seems in Europe after GDPR changes there is a consent alert that needs to be clicked when opening bugreport.apple.com.

When submitting a radar when this is not yet clicked we get error 412. After going to the website and accepting it everything works as expected.

**Comment by vytis** [comment]
I agree, simply a more actionable error message would be enough to fix this.

**Comment by keith** [comment]
https://github.com/br1sk/Sonar/pull/36

**Comment by keith** [comment]
https://github.com/br1sk/brisk/pull/138

**Comment by keith** [comment]
Released in 1.2.0 https://github.com/br1sk/brisk/releases
