### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by keith** [br1sk/brisk#15]
It would be nice if we at least had something for the app icon, and the preferences pane icons.

**Comment by keith** [comment]
We now have an app icon!!! We should use this icon for the menu bar icon, and the prefs pane. Then we'll almost be done.

**Comment by jpsim** [comment]
To clarify, the prefs pane doesn't need the app icon, it needs icons for Apple Radar and Open Radar:

![image](https://cloud.githubusercontent.com/assets/474794/25401999/4c3e8e82-29ac-11e7-9033-2ab0a7da0678.png)

**Comment by keith** [comment]
We were thinking about using the app icon for Apple Radar at least ¯\\_(ツ)_/¯

**Comment by jpsim** [comment]
Apple _does have_ a logo :trollface:

**Comment by ZevEisenberg** [comment]
If the favicon is to be believed, this is the official icon of Radar:

![screen shot 2017-04-25 at 3 17 18 pm](https://cloud.githubusercontent.com/assets/464574/25403439/4f045e1c-29ca-11e7-8ee5-ebf403875651.png)

**Comment by keith** [comment]
Added the bug icon from Radar for the icon in preferences. https://github.com/br1sk/brisk/pull/74

**Comment by keith** [comment]
Related: https://github.com/br1sk/brisk/issues/47

**Comment by keith** [comment]
Using the User icon for Open Radar for now https://github.com/br1sk/brisk/pull/84
