### ISSUE TITLE
Log Out button should not be blue

### ISSUE THREAD

**Issue by ZevEisenberg** [br1sk/brisk#26]
![screen shot 2017-04-12 at 10 43 32 am](https://cloud.githubusercontent.com/assets/464574/24963618/12c962d8-1f6d-11e7-89f4-23d185ccdc3c.png)

According to the storyboard, it also has a default keyboard shortcut of Command-Return. I don't think signing out of iTunes Connect is a common enough action to warrant a keyboard shortcut, especially a secret one (since it doesn't show up in any menus).

**Comment by keith** [comment]
I totally just did this because during development it made testing easier haha

**Comment by keith** [comment]
Removed in the linked PR
