### ISSUE TITLE
Text areas do not redraw themselves

### ISSUE THREAD

**Issue by saagarjha** [br1sk/brisk#30]
I'm having an odd issue where the text areas are don't seem to update at all. I can "type" in them (I've confirmed that the relevant delegate methods are being called, and that their text is changing internally), but nothing shows up. Based on this:

<img width="817" alt="screen shot 2017-04-12 at 16 09 15" src="https://cloud.githubusercontent.com/assets/13786931/24983239/b16e6cbc-1f9a-11e7-8d98-5cabc228b914.png">

which was caused by focusing the text field above it a bunch of times, I'm guessing that the text area isn't redrawing itself properly. Oddly enough, adding a new text view in the storyboard seems to fix the issue.

**Comment by keith** [comment]
Interesting 🤔  let me look into this.

**Comment by funkenstrahlen** [comment]
I have the same problem. Title text field works though.

**Comment by jessesquires** [comment]
Same here. I just played around with this. Looks like an issue with stack view and/or constraints?

I removed and re-added the description textView, then everything was working fine

**Comment by jessesquires** [comment]
confirmed. issue with autolayout constraints. will submit a PR

**Comment by keith** [comment]
I've just pushed 0.1.1 with @jessesquires' fix. Please let me know if it doesn't fix this issue for you!

https://github.com/br1sk/brisk/releases/tag/0.1.1
