### ISSUE TITLE
Text view resizing doesn't work correctly

### ISSUE THREAD

**Issue by keith** [br1sk/brisk#33]
As fallout from fixing https://github.com/br1sk/brisk/issues/30 text views are not all correctly resized:

![image](https://cloud.githubusercontent.com/assets/283886/25048905/e2706fcc-20f3-11e7-936e-1251195c00b9.png)

We should try and figure out how to fix this without rebreaking the much more important issue.

**Comment by saagarjha** [comment]
A possible workaround might be adding constraints so that each of the text views have equal height…

**Comment by keith** [comment]
I'm not looking at this now but I believe they already do :)

**Comment by jessesquires** [comment]
The issue in #30 seemed to be making `descriptionTextView.top` equal to `decriptionLabel.top`

**Comment by ZevEisenberg** [comment]
I can confirm that adding equal height constraints fixes the problem. It's weird that it doesn't just work with the stack view set up the way it is, but the constraints might be a reasonable pragmatic workaround.

**Comment by keith** [comment]
As long as that doesn't break the other case that sgtm

**Comment by keith** [comment]
Not sure when this got fixed, but it works now.

**Comment by saagarjha** [comment]
I'm not quite sure this is completely fixed. If you look closely, it appears that the top text view doesn't actually resize when the window is enlarged:

<img width="817" alt="screen shot 2017-08-20 at 15 10 02" src="https://user-images.githubusercontent.com/13786931/29498888-abe6c2aa-85b9-11e7-9e81-44df57d60e8e.png">

**Comment by keith** [comment]
It looks like it was actually fixed with https://github.com/br1sk/brisk/pull/117

So that will go out in the next release. Thanks!

**Comment by keith** [comment]
I've just released 1.1.1 which has this fix, please let me know if it's not fixed for you! Thanks everyone

**Comment by saagarjha** [comment]
Umm…
<img width="817" alt="screen shot 2017-08-20 at 17 04 23" src="https://user-images.githubusercontent.com/13786931/29499633-d78ebd7a-85ca-11e7-81f8-6a4e509b308f.png">

I really think the issue here isn't your constraints; rather, there's a bug in Cocoa's AutoLayout.

**Comment by keith** [comment]
Ugh. This happens all the time for you? I've never seen this one 🙃

**Comment by saagarjha** [comment]
Yep, it's happening whenever I create a new window. Resizing the window makes it work, though; I guess it forces another layout pass (I had written a similar "solution" a while back  at https://github.com/saagarjha/brisk/commit/87fd52401ea6f4196e6b5690b79896fe63bbdbbb, if you're curious).

**Comment by keith** [comment]
What OS version are you on? I'm happy to merge a fix similar to this one, it's just super annoying that I can't test it as well.

**Comment by saagarjha** [comment]
macOS High Sierra 10.13 Beta (17A344b). If you'd like, I can fast-forward my fork from this repository and create a pull request (and maybe a radar…)

**Comment by keith** [comment]
If that still works that would be great!
