### ISSUE TITLE
Ability to drag and drop attachments

### ISSUE THREAD

**Issue by ZevEisenberg** [br1sk/brisk#35]
You should be able to drag attachments to a drop zone (or to the whole window) to attach them to a radar.

**Comment by keith** [comment]
Totally agree. Punted on this because appkit haha

**Comment by ZevEisenberg** [comment]
If you're going to be doing multiple attachments, I'd do that first, since it's probably easier to add drop zones to multiple uploads than to add drop zones and then try to figure out how to make arbitrarily many of them.

**Comment by keith** [comment]
Released in 1.1.0
