### ISSUE TITLE
Build fails 'out of the box'

### ISSUE THREAD

**Issue by koenvanderdrift** [br1sk/brisk#39]
Just downloaded the project, opened the xcworkspace file in Xcode, and upon build I get the following errors and warnings:

![screen shot 2017-04-15 at 1 48 03 pm](https://cloud.githubusercontent.com/assets/89622/25065721/4d778ec4-21e2-11e7-8e74-0e0730657f72.png)

This is with Xcode 8.3.1.

**Comment by keith** [comment]
You have to run pod install. See https://github.com/br1sk/brisk/issues/25
