### ISSUE TITLE
Submit button is grayed out

### ISSUE THREAD

**Issue by ZevEisenberg** [br1sk/brisk#46]
Version 0.1.1 from the Releases page.
<img width="756" alt="screen shot 2017-04-17 at 12 14 14 am" src="https://cloud.githubusercontent.com/assets/464574/25078618/cf682d46-2302-11e7-91e3-30c7791812ac.png">
Should this be working?

**Comment by keith** [comment]
In this case it's because you have to have something in all fields right now. This means Configuration and notes at least need a space. I'm not sure the best way to handle this moving forward.

**Comment by ZevEisenberg** [comment]
Oh hey, that totally worked. I thought I had tried that, but I guess not. I don't even know what goes in "Configuration." Some hint text would be nice. But if they're all required, maybe just substitute spaces in if you leave fields empty?

**Comment by keith** [comment]
I don't think any fields here are actually "required", the original reason I made them all required was just to sanity check your submissions. Not sure what the best approach is here. I could definitely add the placeholders as a step 1 though.

**Comment by michaelochs** [comment]
I'd like to bump this from a question to a feature request: It should be possible to submit a radar with only one of the main fields filled. It may make sense to ask when clicking ’Submit‘ without having everything filled out, but it should be able to still submit. Reason: When submitting feature requests / enhancements, there often are no steps to reproduce and maybe even no actual behavior.

To sanitize the input a little bit though I propose that at least the title and the description field need to contain some text, as I can't come up with a reason that makes sense to leave these empty. But maybe there are?

**Comment by keith** [comment]
It looks like on Radar web the only option fields that we have that are currently non-optional are Configuration and Notes. I think we might want to mirror this behavior.

Thoughts?

**Comment by keith** [comment]
Also note that for duping the optionality of fields doesn't affect the ability to submit since I fill all other fields with a single space. That's kind of a nasty work around but I think it's nicer for UX.

**Comment by keith** [comment]
Done in https://github.com/br1sk/brisk/pull/86

**Comment by michaelochs** [comment]
> Also note that for duping the optionality of fields doesn't affect the ability to submit since I fill all other fields with a single space. That's kind of a nasty work around but I think it's nicer for UX.

That's no longer necessary as soon now though, right? Does #86 fix that as well?

**Comment by keith** [comment]
Only for those 2 fields yea. I removed the singles spaces for those fields for duping in #86 https://github.com/br1sk/brisk/pull/86/files#diff-a021e3fdf04516435e903458188d120bR44
