### ISSUE TITLE
Enable tabbing between fields

### ISSUE THREAD

**Issue by ZevEisenberg** [br1sk/brisk#52]
Related to #5: if you're in the Description field and you hit Tab, you add a `\t` instead of jumping to the Steps field.

**Comment by keith** [comment]
I can actually make this change super easily, the only thing I'm wondering / worried about is if it will be "expected" relative to "normal" OS behavior.

**Comment by futuretap** [comment]
+1 for tabbing between fields

**Comment by keith** [comment]
The fix for this is here: https://github.com/br1sk/brisk/pull/78

**Comment by keith** [comment]
This is in master and will be out in the next release. Thanks everyone!
