### ISSUE TITLE
Auto-numbered lists in Steps field

### ISSUE THREAD

**Issue by ZevEisenberg** [br1sk/brisk#53]
I usually format my "Steps to reproduce" as a numbered list. It's annoying to have to type the numbers in by hand, especially when I realize I need to add a step in the middle, and then have to update all the numbers after that one. I wonder if Brisk can hook into `NSTextField`'s auto list numbering to detect if I start typing a list, and update accordingly?

**Comment by keith** [comment]
I'm not familiar with the numbered list behavior of `NSTextField` (or maybe you meant `NSTextView`?). Do you mean part of the rich text editing stuff that text edit does? Any API to point me towards?

**Comment by ZevEisenberg** [comment]
Sorry, I don't know how you get this behavior in AppKit. But yes, the rich text stuff that TextEdit does, but then baking it in to plain text on submission.

**Comment by keith** [comment]
AFAICT there's nothing for this in AppKit, I would entertain the idea of merging a PR for this, assuming users could opt out, but I'm going to close this in the meantime.
