### ISSUE TITLE
Inserted emoji reformat input

### ISSUE THREAD

**Issue by kiliankoe** [br1sk/brisk#55]
Sorry for the horrible issue title, not quite sure how to title this.

I wanted to include emojis in my description ('cause Apple engineers need some ❤️ and ✨ too). On inserting one with macOS' emoji picker *something* about my input changed. Typed spaces were much wider, text was monospaced. I've seen something similar happening in the commit text field in SourceTree, but nowhere else before. Not sure what that is, I'm not very familiar with NSTextFields and their API to have something particular in mind.

**Comment by keith** [comment]
Thanks for reporting! I'll look in to this, I don't think I've typed emoji into brisk at all yet

**Comment by keith** [comment]
Oh man, this was a fun one. It seems like AppKit is just totally failing here if you don't provide a font selection for the text view. If you do, the font doesn't change after typing an emoji.

I've fixed this here: https://github.com/br1sk/brisk/pull/67

FWIW when typing an emoji there are still spacing changes in the text view, but it seems like that's just an OS issue:

https://stackoverflow.com/questions/43656445/text-position-shifts-down-font-also-changes-when-an-emoji-is-added-in-nstextvi
https://stackoverflow.com/questions/39460470/how-to-insert-emoji-into-nstextview-without-shifting-the-line-down

**Comment by keith** [comment]
This is fixed on master, I'll probably create a new release with it today.

Thanks for submitting this! Please let me know if you find any more issues!

**Comment by kiliankoe** [comment]
Awesome 🎉 Thanks so much for the fix and also the links and extra info, much appreciated 😊
