### ISSUE TITLE
App behaves weirdly in dock-icon mode

### ISSUE THREAD

**Issue by snej** [br1sk/brisk#56]
I enabled the dock icon preference and relaunched. The app is slightly broken in this mode:

* When launched, its icon appears in the Dock but no window opens, and the previously open app remains active (with its menu bar showing.)
* Clicking the Dock icon causes the window to open and its menu bar to appear. The window works, but the menu bar doesn't: clicks in it do nothing. Very weird.
* After clicking on a different app's window and then in Brisk's window, the menu bar is now enabled.

I've seen issues like this in the past and they usually result from something wrong in the Info.plist.

**Comment by snej** [comment]
(If it's not clear, I want the app to work like a normal app and not a menu extra. I have too many icons in my menu bar already and I don't file bugs many times a day so I don't need a super easy shortcut. So I want to go into the Apps folder in my Dock, click on Brisk to launch it, and have its window come up.)

**Comment by keith** [comment]
> When launched, its icon appears in the Dock but no window opens, and the previously open app remains active (with its menu bar showing.)

This was by design for when there wasn't even a dock option. Maybe when opening with a dock icon, we should open an empty document regardless

> Clicking the Dock icon causes the window to open and its menu bar to appear. The window works, but the menu bar doesn't: clicks in it do nothing. Very weird.
> After clicking on a different app's window and then in Brisk's window, the menu bar is now enabled.

I see this too. Interesting. Will attempt to find a fix

**Comment by keith** [comment]
Fixing the new window when opening Brisk here https://github.com/br1sk/brisk/pull/65

**Comment by keith** [comment]
Fixing the non-responsive menu bar issue here https://github.com/br1sk/brisk/pull/66

**Comment by keith** [comment]
I've fixed both of these and created a new release https://github.com/br1sk/brisk/releases

Please let me know if you see any more issues! Thanks for reporting this!
