### ISSUE TITLE
Support new Radar

### ISSUE THREAD

**Issue by ZevEisenberg** [br1sk/brisk#58]
I didn't see this filed anywhere else. New Radar exited "beta" status today, and it would be great if Brisk supported it. Now that the new/old radar redirect is gone, I suppose it might already work (haven't tested it), but I assume enough has changed on the new site that it won't work without major changes to the page scraping stuff.

**Comment by keith** [comment]
Yep. Will look at this soon. It's definitely changed a lot

**Comment by keith** [comment]
I'm working on the API changes for this here: https://github.com/br1sk/Sonar/pull/16

So far everything is working except for 2 factor auth which I'm testing the changes to now.

**Comment by keith** [comment]
Ok I've tested 2 factor auth as well and everything seems to be working fine.

**Comment by keith** [comment]
I've just released 0.2.0, which fixes this issue! https://github.com/br1sk/brisk/releases/tag/0.2.0

Please let me know if you notice anything weird with it!
