### ISSUE TITLE
"CSRF not found. Maybe the ID is invalid?"

### ISSUE THREAD

**Issue by michaelochs** [br1sk/brisk#61]
I get the error message "CSRF not found. Maybe the ID is invalid?" when submitting a new radar.

**Comment by keith** [comment]
Please update to the newest release from [here](https://github.com/br1sk/brisk/releases). This is caused by API changes on the Radar side with the new UI. This is fixed in the newest release. Let me know if you run into new issues with it!

**Comment by keith** [comment]
(to not lose the radar you've written you can save it to a file and re-open it with the new version)

**Comment by michaelochs** [comment]
Thanks, I did a clean install through brew casks before experiencing this. So I assume brew cask is not up to date then.

**Comment by keith** [comment]
It is [updated with 0.2.0](https://github.com/caskroom/homebrew-cask/blob/c9ce67b71f486daf4d30f06cde8ce39468cbda47/Casks/brisk.rb), maybe you need to `brew update`?
